name: release
on:
  # push:
  #   tags:
  #     - 'v*'
  push:
    branches: [main]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

  publish:
    name: publish ${{ matrix.name }}
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install musl tools.
        run: sudo apt-get install -y musl-tools

      - name: Build in unknown linux
        run: ./scripts/release_tar.sh x86_64-unknown-linux-musl

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-x86_64-unknown-linux-musl
          path: target/x86_64-unknown-linux-musl.tar.gz
